// Package stubs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package stubs

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Car defines model for car.
type Car struct {
	// Brand Brand of a Car
	Brand *string `json:"brand,omitempty"`

	// Model Model of a Car
	Model *string `json:"model,omitempty"`

	// Vin Identifier of a Car
	Vin *Vin `json:"vin,omitempty"`
}

// Vin Identifier of a Car
type Vin = openapi_types.UUID

// PostCarJSONRequestBody defines body for PostCar for application/json ContentType.
type PostCarJSONRequestBody = Car
