// Package stubs provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package stubs

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Brand Brand of a Car
type Brand = string

// Car defines model for car.
type Car struct {
	// Brand Brand of a Car
	Brand *Brand `json:"brand,omitempty"`

	// Model Model of a Car
	Model *Model `json:"model,omitempty"`

	// Vin Identifier of a Car
	Vin *Vin `json:"vin,omitempty"`
}

// Model Model of a Car
type Model = string

// Vin Identifier of a Car
type Vin = openapi_types.UUID

// PostCarJSONBody defines parameters for PostCar.
type PostCarJSONBody struct {
	// Brand Brand of a Car
	Brand *Brand `json:"brand,omitempty"`

	// Model Model of a Car
	Model *Model `json:"model,omitempty"`

	// Vin Identifier of a Car
	Vin *Vin `json:"vin,omitempty"`
}

// PostCarJSONRequestBody defines body for PostCar for application/json ContentType.
type PostCarJSONRequestBody PostCarJSONBody
